# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_test:

    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependecies    
      run: npm install
    - name: Unit test app
      run: npm run test:unit
    - name: Display softuni username
      run: echo 'adelinkz'
  run_ui_test:
   needs:  build_unit_test
   runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependecies    
      run: npm install
    - name: Install playwright 
      run: npx install playwright
    - name: Run the app
      run: npm run start
    - name: Run ui tests
      run: npm run test:ui   